### ISSUE TITLE
Add disclaimer in Compliance Phase doc regarding Test Kitchen

### ISSUE THREAD

**Issue by larry-herz** [chef/chef-web-docs#3317]
**Is your feature request related to a problem? Please describe.**
The documentation for Compliance Phase does not mention any requirements for Test Kitchen, or the fact that this functionality does not yet work with Test Kitchen.

**Describe the solution you'd like**
Add a note to the doc stating that Compliance Phase does not work with test kitchen at this time, then update the docs with whatever changes to kitchen.yml may be needed when it does work.

**Comment by tas50** [comment]
@larry-herz What are you trying to accomplish with Compliance Phase and Test Kitchen exactly?

**Comment by larry-herz** [comment]
Just trying out the Compliance Phase on a new cookbook and trying to use TDD with Test-Kitchen. After failing to find a way to get TK to execute the compliance phase items as part of the converge, I reached out to Slack, and got a response that the Compliance Phase does not yet work from within TK. I was just looking initially for a notice in the docs to not use `[‘audit’][‘compliance_phase’] = true` when using test kitchen, as the converge will fail in running the compliance phase.

LH

**Comment by kagarmoe** [comment]
Looks like you need to add the data collector to the TK `kitchen.yml`:

```
provisioner:
  name: chef_zero
  client_rb:
    data_collector.server_url: 'https://chef-automate.lan/data-collector/v0/'
    data_collector.token: 'huZqgXXW8VtAi8fcGnAvU9jZalw='
```

@dishanktiwari2501 there's more context in this  [internal slack](https://chefio.slack.com/archives/C8EASAK7H/p1635453316071300) message
